# Generated by Django 5.1 on 2024-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_companyprofile_company_reg_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='is_company_admin',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
