# Generated by Django 5.1 on 2024-08-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0004_alter_agentsupportsupplier_company_and_more'),
        ('home', '0003_remove_companyuser_is_company_admin_companyuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
