# Generated by Django 5.1 on 2024-08-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSupportSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('air', 'Air'), ('accommodation', 'Accommodation'), ('ground_transportation', 'Ground Transportation'), ('rail', 'Rail')], max_length=50)),
                ('supplier_name', models.CharField(max_length=100)),
                ('agent_websites', models.TextField(blank=True, null=True)),
                ('contact_numbers', models.TextField(blank=True, null=True)),
                ('group_email', models.TextField(blank=True, null=True)),
                ('general_email', models.TextField(blank=True, null=True)),
                ('account_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('account_manager_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('account_manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
