# Generated by Django 5.1 on 2024-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_1_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_2_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_3_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_4_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='process_4_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
