# Generated by Django 5.1 on 2024-08-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_support', '0002_agentsupportsupplier_process_1_subject_and_more'),
        ('home', '0003_remove_companyuser_is_company_admin_companyuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsupportsupplier',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.companyprofile'),
        ),
    ]
