# Generated by Django 5.1 on 2024-08-31 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('agent_support', '0003_agentsupportsupplier_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.agencyprofile'),
        ),
        migrations.AlterField(
            model_name='agentsupportsupplier',
            name='supplier_type',
            field=models.CharField(choices=[('air', 'Air'), ('accommodation', 'Accommodation'), ('ground_transportation', 'Ground Transportation'), ('rail', 'Rail'), ('other', 'Other')], max_length=50),
        ),
    ]
